# Generated by Django 3.2 on 2021-05-03 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20210503_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='date',
            new_name='created_on',
        ),
        migrations.RenameField(
            model_name='posts',
            old_name='date',
            new_name='created_on',
        ),
    ]
